### ISSUE TITLE
Rounding issue with calculated hatch rate if < 0

### ISSUE THREAD

**Issue by HughZurname** [anhldbk/swarm#1]
Hey 😄 , firstly I just wanted to say thank for the library, it's solved a number of issues that we've experienced with locust4j and saved some time.

Based on my understanding, there seems to be an issue with with the `RateLimiter` setup when it receives a real number value from locust. 

In this scenario, I get the following error:
```
java.lang.IllegalArgumentException: rate must be positive
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at com.google.common.util.concurrent.RateLimiter.setRate(RateLimiter.java:219)
	at com.google.common.util.concurrent.RateLimiter.create(RateLimiter.java:128)
	at com.google.common.util.concurrent.RateLimiter.create(RateLimiter.java:122)
	at com.bigsonata.swarm.Locust.spawnWorkers(Locust.java:259)
	at com.bigsonata.swarm.Locust.startHatching(Locust.java:314)
	at com.bigsonata.swarm.Locust.onMessage(Locust.java:146)
	at com.bigsonata.swarm.Locust.access$600(Locust.java:30)
	at com.bigsonata.swarm.Locust$1.onMessage(Locust.java:90)
	at com.bigsonata.swarm.interop.ZeroTransport$1.process(ZeroTransport.java:93)
	at com.bigsonata.swarm.interop.LoopingThread.run(LoopingThread.java:40)
	at java.lang.Thread.run(Thread.java:748)
```

The locust manager seems to allow for such values for the hatch rate and it looks like you are reading it in as a Float here:

https://github.com/anhldbk/swarm/blob/bfe471b45a681fc761f95dd0a4202248fd6204a9/src/main/java/com/bigsonata/swarm/Locust.java#L144

And the issue seems to start here, where the Float value is converted to an Int and rounded to 0: 

https://github.com/anhldbk/swarm/blob/bfe471b45a681fc761f95dd0a4202248fd6204a9/src/main/java/com/bigsonata/swarm/Locust.java#L146

In cases where you're scaling worker nodes based on your desired load, it's possible that the manager will send a value greater than 0 and less than 1 to the worker, which causes the error above and the worker needs to be restarted in order to work. 

I've solved the issue locally, and I'll link the PR to this issue for your review.

**Comment by anhldbk** [comment]
@HughZurname Thank you so much! Gonna merge it now.
